In [2]:
import numpy as np

In [3]:
# basic array creation
arr=np.array([1,2,3])
list=[1,'Hello',3.5]
print(arr)
print(list)

[1 2 3]
[1, 'Hello', 3.5]


In [4]:
# vectors and matrices
l= [[1,2,3],[4,5,6],[7,8,9]]
print(l)

mat=np.array(l)
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# array generation functions
a1=np.arange(0,11,2) # start,stop,step (stop is exclusive)
print(a1)

a2=np.zeros(6)
print(a2)

a3=np.zeros((2,3))
print(a3)


[ 0  2  4  6  8 10]
[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr=np.linspace(0,10,3) # start,stop,num (num is number of values to generate between start and stop)
arr

array([ 0.,  5., 10.])

In [8]:
# random generation function(using random library) 
# all values are between 0 and 1 this is normalisation
np.random.rand(5)

array([0.2890788 , 0.92517604, 0.03353575, 0.87389116, 0.94240781])

In [9]:
# all values are bw -3 to 3 this is standarisation
np.random.randn(10)

array([ 0.86237924, -0.10549088, -0.21457133,  0.32066588,  0.61404984,
       -0.63376064,  0.60035579,  0.32352217, -1.31388195,  1.64794041])

In [10]:
# generates random integers between 0 and 5
np.random.randint(0,5,10) # start,stop,num (num is number of values to generate between start and stop)

array([3, 1, 3, 1, 3, 3, 4, 3, 2, 1], dtype=int32)

In [11]:
# array attributes
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
# number of eleemtns-size of the array  
arr.size

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


9

In [12]:
# array methods
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.mean())
print(arr.std()) # standard deviation
print(arr.var()) # variance
print(arr.argmax()) # index of max value
print(arr.argmin()) # index of min value

9
1
45
5.0
2.581988897471611
6.666666666666667
8
0


In [ ]:
np.sum(arr,axis=0) # column wise sum
np.sum(arr,axis=1) # row wise sum

array([ 6, 15, 24])

In [14]:
#Reshaping and resizing
arr=np.arange(1,31)
arr
arr2=arr.reshape(5,6) # reshape does not change the original array
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [15]:
# indexing and slicing
arr=np.arange(11,21)
print(arr)
print(arr[1])
print(arr[2:4])
print(arr[:4])
print(arr[:])

[11 12 13 14 15 16 17 18 19 20]
12
[13 14]
[11 12 13 14]
[11 12 13 14 15 16 17 18 19 20]


In [16]:
# numpy indexing and slicing of matrix
arr=np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [17]:
print(arr[4])
print(arr[0,4])

[21 22 23 24 25]
5


In [18]:
print(arr[0:2,1:3]) # first 2 rows and 1st and 3rd column
print(arr[3:,3:]) # from 3rd row and 3rd column to end
print(arr[: , 0:1]) # only first column
print(arr[0:1, :]) # only first row

[[2 3]
 [7 8]]
[[19 20]
 [24 25]
 [29 30]]
[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]]
[[1 2 3 4 5]]


In [19]:
# boolean indexing
arr=np.arange(11,21)
bool_index= arr%2==0
print(bool_index)
arr=arr[bool_index]
print(arr)

[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


In [20]:
# Array operations in numpy
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
# for these operations the arrays should be of same shape
print(a1+a2) # element wise addition
print(a1-a2) # element wise subtraction
print(a1*a2) # element wise multiplication
print(a1/a2) # element wise division
print(a1**a2) # element wise exponentiation


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


In [21]:
# broadcasting in numpy- applying an operation to an array and a scalar value
print(a1+10)
a3= (a1+a2)*2
print(a3)

[11 12 13 14 15]
[14 18 22 26 30]


In [22]:
# when u are slicing an array taken out of an array in numpy it doesnt reflect in the original array- shallow copy
# other - deep copy


In [23]:
# matrix operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b) # element wise addition
print(a-b) # element wise subtraction
print(a*b) # element wise multiplication (this is not matrix multiplication)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [24]:
# matrix multiplication
print(a@b)
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [25]:
# transpose of a matrix
print(a.T)

[[1 3]
 [2 4]]


In [27]:
# advance array manipulation
# stacking
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])

arr1=np.vstack((a,b)) # vertical stacking
print(arr1)
arr2=np.hstack((a,b))
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
