In [2]:
import torch
# 2D empty tensor
x=torch.empty(2,2)
print(x)

# 3D empty tensor
x=torch.empty(2,2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])
tensor([[[6.5923e+32, 7.6231e-43],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])


In [23]:
x=torch.rand(3,3)
print(x)

y=torch.zeros(2,2,2)
print(y)

x=torch.ones(2,2,3)
print(x.size())

# tensor creation using python list
y=torch.tensor([3,5,6,7,9])
print(y)

tensor([[0.2005, 0.1674, 0.6757],
        [0.8511, 0.7437, 0.6582],
        [0.0534, 0.6357, 0.3247]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([2, 2, 3])
tensor([3, 5, 6, 7, 9])


In [ ]:
# Basic operations on tensors
x=torch.tensor([2,2,3])
y=torch.tensor([2,6,6])

# Addition
z1=x+y
z2=torch.add(x,y)
print("z1 : ",z1)
print("z2 : ",z2)

# Inplace addition
y.add_(x)
print("y : ",y)

z1 :  tensor([4, 8, 9])
z2 :  tensor([4, 8, 9])
y :  tensor([4, 8, 9])


In [ ]:
# Subtraction
x=torch.tensor([2,2,3])
y=torch.tensor([2,6,6])

z1=x-y
z2=torch.sub(x,y)

print("z1 : ",z1)
print("z2 : ",z2)


z1 :  tensor([ 0, -4, -3])
z2 :  tensor([ 0, -4, -3])


In [ ]:
# Multiplication
x=torch.tensor([2,2,3])
y=torch.tensor([2,6,6])

z1=x*y
z2=torch.mul(x,y)

print("z1 : ",z1)
print("z2 : ",z2)


z1 :  tensor([ 4, 12, 18])
z2 :  tensor([ 4, 12, 18])
