In [ ]:
import torch # Loads the PyTorch library
# Gives access to tensors, autograd, etc.

# Create tensors- scalar , vector , matrix
# Scalar 0D tensor
x1= torch.tensor(3)
print(x1)
print("x1 shape : " ,x1.shape)

# Vector - 1D tensor
x2= torch.tensor([1,2,3])
print(x2)
print("x3 shape : ",x2.shape)

# Mtrix - 2D tensor
x3=torch.tensor([[1,1,1],
                 [2,2,2],
                 [3,3,3],
                 [4,4,4]])
print(x3)
x3.shape

tensor(3)
x1 shape :  torch.Size([])
tensor([1, 2, 3])
x3 shape :  torch.Size([3])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


torch.Size([4, 3])

In [29]:
# Addition
y1=torch.tensor(3)
z1=torch.add(x1,y1)
print(x1+y1)
print(z1)

y2= torch.tensor([2,3,4])
z2=torch.add(x2,y2)
print(x2+y2)
print(z2)

y3=torch.tensor([[3,3,3,3],
                 [2,2,2,2],
                 [1,1,1,1]])
print(y3.shape)
# z3=torch.add(x3,y3)
# print(x3+y3)
# print(z3)

tensor(6)
tensor(6)
tensor([3, 5, 7])
tensor([3, 5, 7])
torch.Size([3, 4])


In [30]:
# Multiplication
print(x1*y1)
print(x2*y2)
# this does element ise multiplication and not matrix multiplication
#print(x3*y3)
z= x3@y3
print("Shape : ",z.shape)

tensor(9)
tensor([ 2,  6, 12])
Shape :  torch.Size([4, 4])


In [31]:
# Reshaping
x = torch.tensor([1,2,3,4])
y = x.reshape(2,2)
print(y)

a=torch.tensor([[1,2,3],
                [4,5,6]])
b=a.reshape(1,6)
print(b)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2, 3, 4, 5, 6]])
